### ISSUE TITLE
Can't authorize

### ISSUE THREAD

**Issue by forteller** [gglukmann/pocket-reader-extension#1]
When trying to authorize in the pop up I first got a message that the certificate was configured wrong. When I added an exemption I just got to a page saying Forbidden.
![screenshot from 2017-11-17 21-47-40](https://user-images.githubusercontent.com/343561/32968355-d9292edc-cbd8-11e7-8d13-1cb94b1162a7.png)

**Comment by gglukmann** [comment]
Yes, there is a problem with google and firefox auth not redirecting back where they should. I asked from pocket support and they said it is probably not possible to redirect back to a new tab page

**Comment by gglukmann** [comment]
I think this is now fixed. When there are problems with logging in please log into getpocket.com first and then to the extension

**Comment by forteller** [comment]
Thank you! :)
