### ISSUE TITLE
Feature Request: mark item as read when open in a new tab

### ISSUE THREAD

**Issue by hossammourad** [gglukmann/pocket-reader-extension#10]
I've done that in a fork, here is the commit hos4m@dd42935
I'm not sure if you're still maintaining this repo or not (that's why I forked it) if you're just let me know and I'll raise a PR here.

**Comment by hos4m** [comment]
I've done that in a fork, here is the commit https://github.com/hos4m/pocketizer/commit/dd42935292cf152605a1e6d466030ef44a284d7b

**Comment by gglukmann** [comment]
I am maintaining it, just don't have much time to add anything here. Are you sure it should work like that? Me personally would not like to archive an item when clicking on it.

**Comment by hossammourad** [comment]
This is a feature that I see some pocket clients implement and I personally like it, I think that should not be the default behavior of the clicking but it can be connected to a boolean in the settings to toggle it.

**Comment by gglukmann** [comment]
I agree with that, would you want to create a PR?

**Comment by hossammourad** [comment]
Yeah, let me work on the settings toggle and then I'll create a PR.

**Comment by hossammourad** [comment]
Hi, this is how the setting will look like, let me know if you have another suggestion.

![image](https://user-images.githubusercontent.com/4350401/71926794-16f60780-3162-11ea-8f8e-895afc8fdabc.png)

**Comment by gglukmann** [comment]
It is fine

**Comment by hossammourad** [comment]
Done https://github.com/gglukmann/pocketizer/pull/11
