### ISSUE TITLE
Item URL needs to be updated

### ISSUE THREAD

**Issue by ivanmendoza** [gglukmann/pocket-reader-extension#12]
**Describe the bug**
Pocket changes item URL from "https://getpocket.com/a/read/" to "https://app.getpocket.com/read/". So, right now the "Open in Pocket" link redirects to Pocket homepage (app.getpocket.com)

**To Reproduce**
1. Go to Pocketizer list
2. Click "Open in Pocket" link

**Expected behavior**
Open link as Pocket Article view.

**Desktop (please complete the following information):**
 - OS: MacOS, 10.15.2 (Catalina)
 - Browser: Firefox
 - Version: 72.0.2

**Line 209 @ components/Item.js**
https://github.com/gglukmann/pocketizer/blob/dd00ee50941903e4234cafb8671f60eb09aea130/assets/js/components/Item.js#L209

**Comment by gglukmann** [comment]
Thank you! For Firefox it is now in live. Update to version 1.11.12.

**Comment by ivanmendoza** [comment]
Thanks @gglukmann!
