### ISSUE TITLE
Add as section to Firefox Home

### ISSUE THREAD

**Issue by Floppy** [gglukmann/pocket-reader-extension#14]
I find both the Pocketizer list and Firefox Home (with search bar and top sites) really useful. There is a section on Firefox Home for suggestions from Pocket, but it's not customised at all, and I'd love to have that show my pocket list instead.

Would it be possible for Pocketizer to be a section on there instead of its own tab?

It actually looks like the Highlights section should be able to do this, but I think it might just be showing the pages recently saved, not the full archive:

![Screenshot 2020-07-20 at 11 18 40](https://user-images.githubusercontent.com/3565/87927274-e11fcd00-ca7a-11ea-9d19-610983081acd.png)

I'm not sure if this is even something that addons can hook into, my searches haven't turned anything up.

**Comment by gglukmann** [comment]
Hi, Pocketizer can't do that, maybe this could be done with a different extension, but Pocketizer can only access your new tab. But as I can't find anything about that either, I don't think Firefox Home is any way editable.

**Comment by Floppy** [comment]
Yeah, I've been looking around, I think you're right. Ah well. Thanks 👍
