### ISSUE TITLE
Retrieved lists limited to 30 items

### ISSUE THREAD

**Issue by Banus** [gglukmann/pocket-reader-extension#17]
Pocket recently changed the behavior of the [retrieve API](https://getpocket.com/developer/docs/v3/retrieve) and now it returns only the 30 most recent items from either list (Saved or Archived). Thus, a newly installed Pocketizer shows only the 30 most recent items.

The documentation suggest a way to retrieve the full list(s) by sorting from oldest to newest and pass the last item's time to the "since" parameter to retrieve a new chunk, iteratively:

> **Retrieving Full List**: Whenever possible, you should use the since parameter, or count and and offset parameters when retrieving a user's list. After retrieving the list, you should store the current time (which is provided along with the list response) and pass that in the next request for the list. This way the server only needs to return a small set (changes since that time) instead of the user's entire list every time.

**Comment by gglukmann** [comment]
Thank you, I'll fix it

**Comment by gglukmann** [comment]
It looks like Pocket has reverted or fixed this themselves. It now loads everything again. A better solution would be to load them in chuck. I'll create an update for that soon.

**Comment by gglukmann** [comment]
I released the fix. Update your extension to 3.0.0. Let me know if you still have any problems.
