### ISSUE TITLE
[Feature Request] Search bar

### ISSUE THREAD

**Issue by extraymond** [gglukmann/pocket-reader-extension#3]
Hi! First of all, thx for creating this wonderful addon. It makes pocket back in a good workflow now( versus saving tons of links but forget to "read it later"... haha what a irony.).

May I suggest adding search feature in the same view, so we can use it as a catalogue too.
Thx, have a nice day!

**Comment by gglukmann** [comment]
Thanks for the feedback. I'll add it to my todo list.

**Comment by gglukmann** [comment]
Added to 1.4.0!
