### ISSUE TITLE
Recommended and trenidning

### ISSUE THREAD

**Issue by nikanorov** [gglukmann/pocket-reader-extension#4]
Hello! 

Thank you so much for this extension! I read your answer about the lack of official API for the recommended articles. Maybe this could help: https://github.com/Pocket/extension-pocket-new-tab
This looks like almost official API for me. Unfortunately, I have no JS experience to implement this as commit. 

Best regards,
Andrey

**Comment by gglukmann** [comment]
Thank you for this hint. I found the right urls from this repo to get recommended and trending articles. Added to 1.6.0!
