### ISSUE TITLE
An empty list's message isn't encoded

### ISSUE THREAD

**Issue by will-stone** [gglukmann/pocket-reader-extension#5]
Hi. Thanks for this extension. It actually makes Pocket useful!

I've noticed that when I have an empty list the text reads:

```
Looks like you haven't saved anything to Pocket yet!<br><small>Start by clicking the plus icon next to your username.<small>
```

I can see that it's the `Helper.js` file that's responsible but cannot see where the change needs to be made (hence no pull-request).

I'm using Firefox 58.

Please let me know if you'd like any more information.

**Comment by gglukmann** [comment]
Thank you for noticing this bug. I fixed unsafe innerHTML assignment with last release and didn't check for messages that included html. Fix coming in 1.6.3.
