### ISSUE TITLE
Not working correctly

### ISSUE THREAD

**Issue by carlosflorencio** [gglukmann/pocket-reader-extension#6]
Hi,

Just installed to try the extension but doesn't seem to work:

![image](https://user-images.githubusercontent.com/1500881/35766237-ea18de56-08cb-11e8-8c3f-01be200eb865.png)

I am logged in into pocket.
🙂

**Comment by gglukmann** [comment]
Thank you! I had a typo in html with last version and it messed up entire extension. Had it fixed now and extension will work again in 1.6.4 version

**Comment by carlosflorencio** [comment]
Works fine now, great work!

Thanks 🙂
