### ISSUE TITLE
Some UX and preference suggestions, licensing

### ISSUE THREAD

**Issue by inputsh** [gglukmann/pocket-reader-extension#7]
Hi,

I've searched for a solution to see my Pocket list in my new tab and your extension ticked all the boxes!

Been using it for about two days now, and while I'm still exploring it, I'm loving it as a product and would like to suggest some preferences and UX suggestions:

1. **Dark mode:** With all the Pocket versions having an option for the [dark mode](https://help.getpocket.com/article/1119-customizing-your-reading-settings-in-pocket), I don't see why this extension couldn't mimic that behavior.
2. **Preferences:** 
    1. I'm slightly bothered by having to click on "Open in Pocket" to see an article in Pocket. I wish there was a way to reverse that process, so that I would be able to click anywhere on a card and be redirected to Pocket, with a small "View original" label below that would allow me to see the original.
    2. Some option to view tags. Tags, by themselves, are not that useful in the free version. However, they become exceptionally more useful once you have Pocket premium and once they are automatically suggested based on the content. With all that work done by Pocket, it's a shame not to be able to see them.
    3. I'm slightly bothered by the way the extension handles bottom padding of the featured images (I would easily sacrifice cropping top and bottom to make them fit instead of leaving out white space if the image is wide). 
    4. Height of the cards themselves. Loosely associated with the previous thing, the cards themselves seem way too high. On my 14 inch monitor, I only see four articles at once. I've zoomed out the extension to 80% so that I would see the majority of two rows of cards. I would easily sacrifice smaller "My Pocket List" heading (or remove it all together, maybe the Pocket icon is enough?), and some of the featured image height to accomplish this. I would also suggest considering to move the "trending" toggle to the upper "status bar" as well.
    5. Make the status bar fixed, so that it remains visible even while scrolling. Self explanatory, kind of annoying to have to scroll up the entire way if I want to switch to the "recommended" tab for example.
3. Add the license to this project. While you have indicated that you want the MIT license on Mozilla AMO, you haven't added the license to the repository. When not indicating a license, it's considered, by default, that the code is under your copyright. See [this link](https://choosealicense.com/no-permission/), from which I'm sharing a quote below:

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

And, as a first option of me, as a user, in such a case:

> Ask the maintainers nicely to add a license. Unless the software includes strong indications to the contrary, lack of a license is probably an oversight. If the software is hosted on a site like GitHub, open an issue requesting a license and include a link to this site, or if you’re bold and it’s fairly obvious what license is most appropriate, open a pull request to add a license.

**Comment by inputsh** [comment]
I would also like to congratulate you for incorporating suggestions!

Yours is the first third party Pocket integration I've seen which shows me suggestions, and I know for a fact that suggestions aren't easily available over the current version of the API, so kudos to you! 

I can't wait to find enough time to fiddle with the code to see how you've done it.

**Comment by gglukmann** [comment]
Thank you for this list!

1. Dark mode - sure, great idea.
2. i. I like to go to the website that is providing the content and not to pockets view. I have many coding articles and pocket can't handle all the code examples. That's why I have made it like this.
ii. I'll have to figure that tags system out, I don't use it myself and I don't have premium.
iii. This can be fixed.
iv. Will fix with previous point.
v. Will do.
3. I'll add MIT to repo.

I'll start adding those features. If you want to code too, you can make pull requests. Pocket API does have recommendations and trending items but they are not documented, I found that from Pockets own extension repo.

**Comment by gglukmann** [comment]
Added tags to 1.9.0 version! Everything else looks like is done too.
