### ISSUE TITLE
Be more descriptive at AMO

### ISSUE THREAD

**Issue by grahamperrin** [gglukmann/pocket-reader-extension#9]
https://addons.mozilla.org/addon/new-tab-pocket/ there's no description, please can you add one? 

Include a worded hint of what's in one of the screenshots: 

> Google and Firefox authentication does not redirect back to extension.

In other words, unless I'm missing something, I can't use my Firefox account to log in (and IIRC it was with this account that I began using Pocket, so I can't use the extension).

**Comment by gglukmann** [comment]
Yeah redirecting back from social login doesn't go back to extension somehow. If you only use Firefox login then you can't login into extension. I can add that to description. But I think you can set a password in Pocket website and then login with that as workaround.
